name: Cypress Tests

on:
  workflow_dispatch:
  
jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node-18.16.0-chrome-113.0.5672.92-1-ff-113.0-edge-113.0.1774.35-1
      options: --user 1001
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2
      
      - name: Install Dependencies
        run: yarn install
      
      - name: Run E2e Tests
        run: npx cypress run
      
